spring:
  application:
    name: FLUX
  datasource:
    url: jdbc:mysql://localhost:3306/flux_db
    username: flux
    password: flux
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  server:
    port: 8080
  web:
    cors:
      allowed-origins: "http://localhost:8000"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
      cors:
        allowed-origins: "http://localhost:8000"
        allowed-methods: "*"
        allowed-headers: "*"
        allow-credentials: true
  jmx:
    enabled: true
    server:
      port: 1099
