spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_HIBERNATE_DIALECT}
        format_sql: true
    show-sql: ${SPRING_JPA_SHOW_SQL}
  server:
    port: ${SPRING_SERVER_PORT}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET}
            redirect-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI}
            authorization-grant-type: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_AUTHORIZATION_GRANT_TYPE}
            scope:
              - ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE_PROFILE}
              - ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE_EMAIL}
          naver:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_ID}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_SECRET}
            redirect-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_REDIRECT_URI}
            client-name: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_NAME}
            authorization-grant-type: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_AUTHORIZATION_GRANT_TYPE}
            scope:
              - ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_SCOPE_NAME}
              - ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_SCOPE_EMAIL}
        provider:
          naver:
            authorization-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_NAVER_AUTHORIZATION_URI}
            token-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_NAVER_TOKEN_URI}
            user-info-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_NAVER_USER_INFO_URI}
            user-name-attribute: ${SPRING_SECURITY_OAUTH2_PROVIDER_NAVER_USER_NAME_ATTRIBUTE}
  servlet:
    multipart:
      enabled: ${SPRING_SERVLET_MULTIPART_ENABLED}
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE}
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE}
    mvc:
      static-path-pattern: ${SPRING_SERVLET_MVC_STATIC_PATH_PATTERN}
app:
  auth:
    tokenSecret: ${APP_AUTH_TOKEN_SECRET}
    tokenExpirationMsec: ${APP_AUTH_TOKEN_EXPIRATION_MSEC}
  cors:
    allowedOrigins:
      - ${APP_CORS_ALLOWED_ORIGINS}
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT}
    com.flux.auth: ${LOGGING_LEVEL_COM_FLUX_AUTH}
    org.springframework.security: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY}
springdoc:
  swagger-ui:
    path: ${SPRINGDOC_SWAGGER_UI_PATH}
    groups-order: ${SPRINGDOC_SWAGGER_UI_GROUPS_ORDER}
    tags-sorter: ${SPRINGDOC_SWAGGER_UI_TAGS_SORTER}
    operations-sorter: ${SPRINGDOC_SWAGGER_UI_OPERATIONS_SORTER}
  paths-to-match:
    - ${SPRINGDOC_PATHS_TO_MATCH}
