spring:
  application:
    name: ${SPRING_APPLICATION_NAME:FLUX}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/flux_db}
    username: ${SPRING_DATASOURCE_USERNAME:flux}
    password: ${SPRING_DATASOURCE_PASSWORD:flux}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}
        format_sql: true
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
  server:
    port: ${SPRING_SERVER_PORT:8080}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID:1009714069325-ktbie6b6ipt0m71dkdgv21gnqsnk11l4.apps.googleusercontent.com}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET: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}
            redirect-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_REDIRECT_URI:http://localhost:8000/login/oauth2/code/google}
            authorization-grant-type: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_AUTHORIZATION_GRANT_TYPE:authorization_code}
            scope:
              - ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE_PROFILE:profile}
              - ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_SCOPE_EMAIL:email}
          naver:
            client-id: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_ID:teR1JDcGa4Dv2AAhrfpv}
            client-secret: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_SECRET:rJZ2lcOJQk}
            redirect-uri: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_REDIRECT_URI:http://localhost:8000/login/oauth2/code/naver}
            client-name: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_CLIENT_NAME:naver}
            authorization-grant-type: ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_AUTHORIZATION_GRANT_TYPE:authorization_code}
            scope:
              - ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_SCOPE_NAME:name}
              - ${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_NAVER_SCOPE_EMAIL:email}
        provider:
          naver:
            authorization-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_NAVER_AUTHORIZATION_URI:https://nid.naver.com/oauth2.0/authorize}
            token-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_NAVER_TOKEN_URI:https://nid.naver.com/oauth2.0/token}
            user-info-uri: ${SPRING_SECURITY_OAUTH2_PROVIDER_NAVER_USER_INFO_URI:https://openapi.naver.com/v1/nid/me}
            user-name-attribute: ${SPRING_SECURITY_OAUTH2_PROVIDER_NAVER_USER_NAME_ATTRIBUTE:response.id}
  servlet:
    multipart:
      enabled: ${SPRING_SERVLET_MULTIPART_ENABLED:true}
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:10MB}
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:10MB}
    mvc:
      static-path-pattern: ${SPRING_SERVLET_MVC_STATIC_PATH_PATTERN:/static/**}
app:
  auth:
    tokenSecret: ${APP_AUTH_TOKEN_SECRET:04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1}
    tokenExpirationMsec: ${APP_AUTH_TOKEN_EXPIRATION_MSEC:864000000}
  cors:
    allowedOrigins:
      - ${APP_CORS_ALLOWED_ORIGINS:http://localhost:8000}
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.flux.auth: ${LOGGING_LEVEL_COM_FLUX_AUTH:DEBUG}
    org.springframework.security: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY:DEBUG}
springdoc:
  swagger-ui:
    path: ${SPRINGDOC_SWAGGER_UI_PATH:/api-test}
    groups-order: ${SPRINGDOC_SWAGGER_UI_GROUPS_ORDER:DESC}
    tags-sorter: ${SPRINGDOC_SWAGGER_UI_TAGS_SORTER:alpha}
    operations-sorter: ${SPRINGDOC_SWAGGER_UI_OPERATIONS_SORTER:method}
  paths-to-match:
    - ${SPRINGDOC_PATHS_TO_MATCH:/api/v1/**}
